motor_info:
        min_thrust: 1 #[N]
        max_thrust: 16.5 #[N]
        abs_max_pwm: 0.95
        force_landing_thrust: 6.5 #[N]
        m_f_rate: -0.0172
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 4
        ref1:
                voltage: 25.2
                polynominal2: 0.07983707 # x10
                polynominal1: -6.627443098 # x10
                polynominal0: 12.3593793002 # x1
        ref2:
                voltage: 24.2
                polynominal2: 0.078085358 # x10
                polynominal1: -6.641338225 # x10
                polynominal0: 12.9797798522 # x1
        ref3:
                voltage: 23.2
                polynominal2: 0.074527175 # x10
                polynominal1: -6.440853637 # x10
                polynominal0: 12.9565178437 # x1
        ref4:
                voltage: 22.2
                polynominal2: 0.071758366 # x10
                polynominal1: -6.346135548 # x10
                polynominal0: 13.2669467083 # x1
