<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx" >

  <!-- basic kinematics model -->
  <xacro:include filename="$(find hydrus)/urdf/common.xacro" />
  <xacro:include filename="$(find hydrus)/urdf/link.urdf.xacro" />
  <xacro:include filename="$(find mbzirc2020_common)/urdf/fixed_link.urdf.xacro" />

  <xacro:macro name="robot_model" params="tilt_angle:=0 downward_vio:=1 horizontal_vio:=0 default_battery:=1 with_leg:=1 with_gps:=1">

    <xacro:if value="${tilt_angle == 0}"> <!--no tilt angle-->
      <xacro:hydrusx_link links="4" self="1" rotor_direction="-1" with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_mode="0" />
      <xacro:hydrusx_fixed_link self="2" rotor_direction="1"  with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_angle = "0" />
      <xacro:hydrusx_fixed_link self="3" rotor_direction="-1" with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_angle = "0" />
      <xacro:hydrusx_link links="4" self="4" rotor_direction="1"  with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_mode="0" />
    </xacro:if>
    <xacro:unless value="${tilt_angle == 0}">
      <xacro:hydrusx_link links="4" self="1" rotor_direction="-1" with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_mode="1" tilt_angle="${tilt_angle}" />
      <xacro:hydrusx_fixed_link self="2" rotor_direction="1"  with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_angle = "${tilt_angle}" />
      <xacro:hydrusx_fixed_link self="3" rotor_direction="-1" with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_angle = "${tilt_angle}" />
      <xacro:hydrusx_link links="4" self="4" rotor_direction="1"  with_battery = "${default_battery}" with_leg = "${with_leg}" tilt_mode="1" tilt_angle="${tilt_angle}"/>
    </xacro:unless>

    <!-- onboard -->
    <!-- 1.  processor -->
    <!-- 1.1 flight controller -->
    <xacro:extra_module name = "fc" parent = "link2" visible = "1"
                        model_url = "package://mbzirc2020_common/urdf/mesh/modules/processor/spinal_fixed_joint.dae">
      <origin xyz="${link_length / 2 + 0.2432} 0.03951 -0.002" rpy="0 0 0"/>
      <inertial>
        <mass value = "0.0416" />
        <origin xyz="0.0136 0.004 0" rpy="0 0 0"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00002"/>
      </inertial>
    </xacro:extra_module>
    <!-- end: flight controller -->

    <!-- 1.2 processor: neuron for link3 -->
    <xacro:extra_module name = "neuron3" parent = "link2" visible = "1"
                        model_url = "package://mbzirc2020_common/urdf/mesh/modules/processor/neuron_unit.dae" >
      <origin xyz="${link_length / 2 + 0.315} 0.07 0.015" rpy="0 0 0"/>
      <inertial>
        <mass value = "0.01" />
        <origin xyz="0 0  0.01" rpy="0 0 0"/>
        <inertia
            ixx="0.00000" ixy="0.0" ixz="0.0"
            iyy="0.00000" iyz="0.0"
            izz="0.00000"/>
      </inertial>
    </xacro:extra_module>
    <!-- end: processor: neuron -->

    <!-- 2.  sensor -->
    <!-- 2.1 leddar one -->
    <xacro:extra_module name = "leddarone" parent = "link2" visible = "1"
                        model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/ledder_one_fixed_joint_unit.dae">
      <origin xyz="${link_length/2 + 0.31814} 0.05614 -0.022" rpy="${pi} 0 0"/>
      <inertial>
        <origin xyz="-0.008 0.0 0.0" rpy="0 0 0"/>
        <mass value="0.02"/>
        <inertia
            ixx="0.0" iyy="0.0" izz="0.0"
            ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
    </xacro:extra_module>
    <!-- end: leddar one -->

    <!-- 2.2 gps -->
    <xacro:if value="${with_gps == 1}">
      <xacro:extra_module name = "gps" parent = "link2" visible = "1"
                          model_url = "package://hydrus/urdf/mesh/sensor/gps_ublox_m8n.dae">
        <origin xyz="${link_length/2 + 0.2446} 0.0554 0.121" rpy="0 0 0"/>
        <inertial>
          <origin xyz="0.000000 0.000000 -0.008" rpy="0 0 0"/>
          <mass value="0.059"/>
          <inertia
              ixx="0.00006" iyy="0.00006" izz="0.000007"
              ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
        </inertial>
      </xacro:extra_module>
      <xacro:extra_module name = "magnet" parent = "gps">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertial>
          <mass value = "0.00001" />
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </xacro:extra_module>
    </xacro:if>
    <!-- end: gps -->

    <!-- 2.3 downwards rs-t265 (VIO) -->
    <xacro:if value="${downward_vio == 1}">
      <xacro:extra_module name = "realsense1_pose_frame" parent = "link2" visible = "1"
                          model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/downward_realsense_unit.STL">
	<origin xyz="${link_length/2 + 0.127} 0.0 -0.022" rpy="0 ${pi/2} ${pi/2}"/>
	<inertial>
          <mass value = "0.065" /> <!-- sensor + usb-cable -->
          <origin xyz="-0.009 -0.01 0" rpy="0 0 0"/>
          <inertia
              ixx="0.0" ixy="0.0" ixz="0.0"
              iyy="0.0" iyz="0.0"
              izz="0.0"/>
	</inertial>
      </xacro:extra_module>
    </xacro:if>
    <!-- end: rs-5265 -->

    <!-- 2.4 horizontal rs-t265 (option VIO) -->
    <xacro:if value="${horizontal_vio == 1}">
        <xacro:extra_module name = "realsense2_pose_frame" parent = "link2" visible = "1"
        model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/center_leg_rs_t265_unit.STL">
        <origin xyz="${link_length/2 + 0.3281} -0.00114 -0.04" rpy="0 0 ${-pi/4}"/>
        <inertial>
        <mass value = "0.073" />
        <origin xyz="-0.01 -0.007 0" rpy="0 0 0"/>
        <inertia
        ixx="0.0" ixy="0.0" ixz="0.0"
        iyy="0.0" iyz="0.0"
        izz="0.0"/>
        </inertial>
        </xacro:extra_module>
    </xacro:if>
    <!-- end: rs-5265 -->

  </xacro:macro>

</robot>
