grasp_joint_angle: [1.4, 1.4]
ungrasp_joint_angle: [0.9, 0.9]
preshape_joint_angle: [0.78, 0.78]
reset_joint_angle: [1.5, 1.5]

object_translation: [0.1, 0.5, 0.0] #in link2 frame
object_yaw: -0.785
object_mass: 1.0

object_num: 1
object_lookdown_height: 3.0
object_approach_height: 1.2
object_grasping_height: 0.2
object_yaw_thresh: 0.3
global_first_object_pos: [-1.5, 0.0] #need if no recognition mode
object_interval: 0.6 #object center to center in a lane
lane_interval: 0.75 #constant
#global_lookdown_pos_gps: [35.89514880, 139.9447680] #lati, long
global_lookdown_pos_gps: [35.89515520, 139.94476800] #lati, long 
global_object_yaw: 0.0

grasping_point: [-0.445, 0.445, 0.00] #in fc frame
grasping_yaw: 2.356 #in fc frame
grasp_land_mode: True
joint_torque_thresh: 5 #[Nm]

global_place_channel_front_pos_gps: [35.89514880, 139.9447680]
global_place_channel_back_pos_gps: [35.89514980, 139.9447680]
global_place_channel_z: 1.7 #[m]
place_z_margin: 0.8 #[m]
place_z_offset: 1.3 #[m]
channel_tf_frame_id: channel_center
