# parameters for script/motion.py

control_rate : 1.0

area_corners : [[0, 0], [1, 1]]
search_height : 1.2
search_grid_size : 0.25
reach_margin : 0.15
target_timeout : 1.0
approach_height : 1.2
descending_height : 1.2
approach_margin : 0.15
height_margin : 0.15
covering_pre_height : 1.2
covering_post_height : 0.2
covering_move_dist : 0.4

