# parameters for script/motion.py

control_rate : 5.0

area_corners : [[0, 0], [10, 10]]
search_height : 3.0
search_grid_size : 2.0
reach_margin : 0.2
target_timeout : 1.0
approach_height : 3.0
descending_height : 1.5
approach_margin : 0.05
height_margin : 0.05
covering_pre_height : 1.5
covering_post_height : 0.2
covering_move_dist : 0.8

