hls_color_filter_img:
  h_limit_max: 22
  h_limit_min: 323
  l_limit_max: 225
  l_limit_min: 30
  s_limit_max: 256
  s_limit_min: 30
  use_camera_info: false
  queue_size: 10

hsi_color_filter:
  h_limit_max: -35
  h_limit_min: 21
  s_limit_max: 217
  s_limit_min: 23
  i_limit_max: 216
  i_limit_min: 31

rectangle_detection_color:
  target_object_area: 0.09
  target_object_area_margin: 0.06
