grasp_joint_angle: [1.5, 1.5]
ungrasp_joint_angle: [0.9, 0.9]
preshape_joint_angle: [0.75, 0.75]
reset_joint_angle: [1.5, 1.5]

object_translation: [0.1, 0.5, 0.0] #in link2 frame
object_yaw: -0.785

object_grasping_height: 0.2
object_yaw_thresh: 0.3
global_first_object_pos: [-1.5, 0.0] #need if no recognition mode
object_interval: 0.6 #object center to center in a lane
lane_interval: 0.75 #constant
object_pos_thresh: 0.15
adjust_grasp_image_type: color #depth or color

global_object_yaw: -1.8606593608856201
recognition_wait: 1.0

grasping_yaw: 2.356 #in fc frame
grasp_land_mode: true
reset_realsense_odom: true
joint_torque_thresh: 5 #[Nm]
stop_if_grasp_failed: true

place_channel_length: 4.0
global_place_channel_z: 2.0 #[m]
place_z_margin: 1.0 #[m]
place_z_offset: 1.4 #[m]
channel_pos_thresh: 0.3
channel_tf_frame_id: channel_center

disable_alt_sensor: True
alt_sensor_service_name: /estimator/sensor_plugin/alt1/estimate_flag

#search motion params

lookdown:
  grid: [[0, 1], [0, 0], [0, -1], [1, -1], [1, 0], [1, 1], [2, 1], [2, 0], [2, -1], [3, -1], [3, 0], [3, 1], [4, 1], [4, 0], [4, -1]]
  grid_scale_x: 1.2
  grid_scale_y: 1.0
  grid_search_timeout: 8

adjust_grasp:
  #grid: [[-1, 2], [-1, 1], [-1, 0], [-1, -1], [-1, -2], [0, -2], [0, -1], [0, 0], [0, 1], [0, 2], [1, 2], [1, 1], [1, 0], [1, -1], [1, -2], [2, -2], [2, -1], [2, 0], [2, 1], [2, 2], [3, 2], [3, 1], [3, 0], [3, -1], [3, -2]]
  grid: [[0, -2], [0, -1], [0, 0], [0, 1], [0, 2], [1, 2], [1, 1], [1, 0], [1, -1], [1, -2], [2, -2], [2, -1], [2, 0], [2, 1], [2, 2], [3, 2], [3, 1], [3, 0], [3, -1], [3, -2]]
#  grid_scale_x: 0.7
#  grid_scale_y: 0.5
  grid_search_timeout: 5

adjust_place:
  grid: [[0, -1], [0, 0], [0, 1], [0, 2], [-1, 2], [-1, 1], [-1, 0], [-1, -1], [-1, -2], [0, -2], [1, -2], [1, -1], [1, 0], [1, 1], [1, 2]]
  grid_scale_x: 1.0
  grid_scale_y: 1.0
  grid_search_timeout: 7
