grasp_joint_angle: [1.4, 1.4]
ungrasp_joint_angle: [0.9, 0.9]
preshape_joint_angle: [0.78, 0.78]
reset_joint_angle: [1.5, 1.5]
open_joint_angle: [0.6, 0.6]

object_translation_in_link2: [0.1, 0.5, 0.0] #in link2 frame
object_yaw_in_link2: -0.785

object_lookdown_height: 3.0
object_approach_height: 1.2

scan_area_velocity: 0.2
scan_area_length: 4.0
scan_area_pos_thre: 0.3
scan_rp_thre: 0.1

pick_visual_servoing_z_diff: 0.03

grasp_horizontal_interpolation_time: 50 # *0.1 -> sec
grasp_vertical_interpolation_time: 100 # *0.1 -> sec

object_grasping_height: 0.2
object_yaw_thresh: 0.2
object_pos_thresh: 0.15
adjust_grasp_image_type: color

global_object_yaw: 3.141
recognition_wait: 1.0

grasping_yaw: 0.785 #in link3 frame
grasping_point: [0.4955, 0.4955, -0.2] #in link3 frame
grasping_yaw_in_fc: 2.356

joint_torque_thresh: 3 #[Nm]
stop_if_grasp_failed: false

place_lookdown_height: 3.0 #[m] should be higher than 2.0[m]
place_height: 2.5 #[m] should be height than 2.0[m]
channel_pos_thresh: 0.3
channel_tf_frame_id: channel_center

alt_sensor_service_name: sensor_plugin/alt1/estimate_flag
plane_detection_service_name: sensor_plugin/plane_detection1/estimate_flag

#search motion params

adjust_place:
  grid: [[0, -1], [0, 0], [0, 1], [0, 2], [-1, 2], [-1, 1], [-1, 0], [-1, -1], [-1, -2], [0, -2], [1, -2], [1, -1], [1, 0], [1, 1], [1, 2]]
  grid_scale_x: 0.8
  grid_scale_y: 0.8
  grid_search_timeout: 10
