motor_info:
        min_thrust: 1 #[N]
        max_thrust: 16 #[N]
        abs_max_pwm: 0.9
        force_landing_thrust: 6.5 #[N]
        m_f_rate: -0.01636
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 4
        ref1:        
                voltage: 25.2
                polynominal2: 0.059976113 # x10
                polynominal1: -3.660731 # x10
                polynominal0: 2.125751 # x1
        ref2:
                voltage: 24.2        
                polynominal2: 0.06047878 # x10
                polynominal1: -4.131479 # x10
                polynominal0: 4.587418 # x1
        ref3:
                voltage: 23.2        
                polynominal2: 0.056440896 # x10
                polynominal1: -3.8695979 # x10
                polynominal0: 4.2894956 # x1
        ref4:
                voltage: 22.2        
                polynominal2: 0.05945578 # x10
                polynominal1: -4.7306816 # x10
                polynominal0: 8.0611266 # x1                 