hydrusx:
  servo_controller:
    legs:
      ctrl_pub_topic: /extra_servo_cmd
      torque_pub_topic: /extra_servo_torque_enable

      # for simulation
      simulation:
        pid: {p: 500, i: 5, d: 2.0, i_clamp_min: -50.0, i_clamp_max: 50.0}

        init_value: 0 # m
        type: effort_controllers/JointPositionController

      controller1:
        id: 0
        name: actuated_leg1_joint
        angle_sgn: -1
        angle_scale: 0.00006571428 # please fix
        zero_point_offset: 700 # please fix

      controller2:
        id: 2
        name: actuated_leg2_joint
        angle_sgn: 1
        angle_scale: 0.00006571428 # please fix
        zero_point_offset: 1000 # please fix


aerial_robot_base_node:
        navigator:
                takeoff_height: 0.6
