<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx" >

  <!-- basic kinematics model -->
  <xacro:include filename="$(find hydrus)/urdf/common.xacro" />
  <xacro:include filename="$(find hydrus)/urdf/link.urdf.xacro" />

  <xacro:hydrusx_link links="4" self="1" rotor_direction="-1" with_battery = "0" with_leg = "0"/>
  <xacro:hydrusx_link links="4" self="2" rotor_direction="1"  with_battery = "0" with_leg = "0"/>
  <xacro:hydrusx_link links="4" self="3" rotor_direction="-1" with_battery = "0" with_leg = "1"/>
  <xacro:hydrusx_link links="4" self="4" rotor_direction="1"  with_battery = "0" with_leg = "0"/>

  <!-- actuated legs -->
  <!-- in the second link -->
  <xacro:extra_module name = "actuated_leg1_stationary_part" parent = "link2" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/modules/mechanical/actuated_leg_stationary_part.dae">
    <origin xyz="${head_leg_offset} 0 0" rpy="${-pi/2} 0 0"/>
    <inertial>
      <mass value = "0.142" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001"/>
    </inertial>
  </xacro:extra_module>
  
  <joint name="actuated_leg1_joint" type="fixed">
    <parent link="actuated_leg1_stationary_part"/>
    <child link="actuated_leg1_movable_part"/>
    <origin rpy="${-pi/2} 0 ${pi}" xyz="-0.0115 0.1042 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="actuated_leg1_movable_part">
    <inertial>
      <origin xyz="-0.002860 0.000000 -0.089840" rpy="0 0 0"/>
      <mass value="0.107000"/>
      <inertia
          ixx="0.002466" iyy="0.003026" izz="0.000699"
          ixy="0.000150" ixz="0.001147" iyz="0.000280"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
      <geometry>
        <mesh filename="package://hydrus/urdf/mesh/modules/mechanical/actuated_leg_movable_part.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0025 0 -0.128"/>
      <geometry>
        <sphere radius="${55 / 2 * 0.001}"/>
      </geometry>
    </collision>
  </link>
  
  <!-- in the thrid links -->
  <xacro:extra_module name = "actuated_leg2_stationary_part" parent = "link3" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/modules/mechanical/actuated_leg_stationary_part.dae">
    <origin xyz="${link_length - head_leg_offset} 0.0 0" rpy="${-pi/2} 0 ${pi}"/>
    <inertial>
      <mass value = "0.142" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001"/>
    </inertial>
  </xacro:extra_module>

  <joint name="actuated_leg2_joint" type="fixed">
    <parent link="actuated_leg2_stationary_part"/>
    <child link="actuated_leg2_movable_part"/>
    <origin rpy="${-pi/2} 0 ${pi}" xyz="-0.0115 0.1042 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="actuated_leg2_movable_part">
    <inertial>
      <origin xyz="-0.002860 0.000000 -0.089840" rpy="0 0 0"/>
      <mass value="0.107000"/>
      <inertia
          ixx="0.002466" iyy="0.003026" izz="0.000699"
          ixy="0.000150" ixz="0.001147" iyz="0.000280"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
      <geometry>
        <mesh filename="package://hydrus/urdf/mesh/modules/mechanical/actuated_leg_movable_part.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0025 0 -0.128"/>
      <geometry>
        <sphere radius="${55 / 2 * 0.001}"/>
      </geometry>
    </collision>
  </link>

  <!-- omniwheel normal legs -->  
  <!-- in the first link -->
  <joint name="link1_to_leg1" type="fixed">
    <parent link="link1"/>
    <child link="omni_leg1"/>
    <origin xyz="${head_leg_offset} 0.0 0" rpy="0 0 0"/>
    <origin rpy="0 0 0" xyz="-0.0115 0 -0.0115"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="omni_leg1">
    <inertial>
      <origin xyz="0.000000 0.000000 -0.093340" rpy="0 0 0"/>
      <mass value="0.072000"/>
      <inertia
          ixx="-0.000617" iyy="-0.000627" izz="0.0000"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
      <geometry>
        <mesh filename="package://hydrus/urdf/mesh/modules/mechanical/passive_stationary_part.dae"/>
      </geometry>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 -0.002 -0.14"/>
        <geometry>
          <sphere radius="${55 / 2 * 0.001}"/>
        </geometry>
    </collision>
  </link>

  <!-- in the forth link -->
  <joint name="link4_to_leg3" type="fixed">
    <parent link="link4"/>
    <child link="omni_leg2"/>
    <origin xyz="${end_leg_offset} 0.0 0" rpy="0 0 0"/>
    <origin rpy="0 0 0" xyz="-0.0115 0 -0.0115"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="omni_leg2">
    <inertial>
      <origin xyz="0.000000 0.000000 -0.093340" rpy="0 0 0"/>
      <mass value="0.072000"/>
      <inertia
          ixx="-0.000617" iyy="-0.000627" izz="0.0000"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
      <geometry>
        <mesh filename="package://hydrus/urdf/mesh/modules/mechanical/passive_stationary_part.dae"/>
      </geometry>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 -0.002 -0.14"/>
        <geometry>
          <sphere radius="${55 / 2 * 0.001}"/>
        </geometry>
    </collision>
  </link>

  <gazebo reference="actuated_leg1_movable_part">
    <mu1>0.11</mu1>
    <mu2>0.11</mu2>
    <fdir1>1 1 0</fdir1>
    <minDepth>0.00</minDepth>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <gazebo reference="actuated_leg2_movable_part">
    <mu1>0.11</mu1>
    <mu2>0.11</mu2>
    <fdir1>1 1 0</fdir1>
    <minDepth>0.00</minDepth>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <gazebo reference="omni_leg1">
    <mu1>0.11</mu1>
    <mu2>0.11</mu2>
    <fdir1>1 1 0</fdir1>
    <minDepth>0.00</minDepth>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <gazebo reference="omni_leg2">
    <mu1>0.11</mu1>
    <mu2>0.11</mu2>
    <fdir1>1 1 0</fdir1>
    <minDepth>0.00</minDepth>
    <selfCollide>false</selfCollide>
  </gazebo>

  <!-- special battery arrangement -->
  <xacro:extra_module name = "bat1" parent = "link1" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" >
    <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.4108"/>
      <inertia
          ixx="0.0001" iyy="0.0006" izz="0.0006"
          ixy="0.0" ixz="0.0"  iyz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <xacro:extra_module name = "bat2" parent = "link4" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" >
    <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.4108"/>
      <inertia
          ixx="0.0001" iyy="0.0006" izz="0.0006"
          ixy="0.0" ixz="0.0"  iyz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <!-- onboard -->
  <!-- 1.  processor -->
  <!-- 1.1 flight controller -->
  <xacro:extra_module name = "fc" parent = "link2" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/ver2/flight_controller/spinal.dae"> <!-- same with intel euclid -->
    <origin xyz="${link_length / 2 + 0.2221} ${-4.4*0.001} 0.02135" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.05" />
      <origin xyz="${13*0.001} ${4.4*0.001} ${-9*0.001}" rpy="0 0 0"/>
      <inertia
          ixx="0.00001" ixy="0.0" ixz="0.0"
          iyy="0.00001" iyz="0.0"
          izz="0.00002"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: flight controller -->

  <!-- 1.2 processor: jetson tx2 -->
  <!-- confirm the inertial parameter with real machine -->
  <xacro:extra_module name = "pc" parent = "link3" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/ver2/processor/jetson_tx2_unit.dae" >
    <origin xyz="${link_length / 2 - 0.23775} 0.0 ${-0.01}" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.181" />
      <origin xyz="${18 * 0.001} ${4 * 0.001} ${-18 * 0.001}" rpy="0 0 0"/>
      <inertia
          ixx="0.00007" ixy="0.0" ixz="0.0"
          iyy="0.00003" iyz="0.0"
          izz="0.00009"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: processor: jetson tx2 -->

  <!-- 2.  sensor -->
  <!-- 2.1 leddar one -->
  <xacro:extra_module name = "leddarone" parent = "link3" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/sensor/leddar_one_tx2_attached_mode.dae">
    <origin xyz="${link_length/2 - 0.1855} 0.0 -0.0626" rpy="${pi} 0 0"/>
    <inertial>
      <origin xyz="-0.008 0.0 0.0" rpy="0 0 0"/>
      <mass value="0.025"/>
      <inertia
          ixx="0.00001" iyy="0.000006" izz="0.00001"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: leddar one -->

  <!-- 2.2 gps -->
  <xacro:extra_module name = "gps" parent = "link2" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/sensor/gps_ublox_m8n.dae">
    <origin xyz="${link_length/2 + 0.1925} 0.0 0.152" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0.000000 0.000000 -0.013" rpy="0 0 0"/>
      <mass value="0.042"/>
      <inertia
          ixx="0.00006" iyy="0.00006" izz="0.000007"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
  </xacro:extra_module>
  <xacro:extra_module name = "magnet" parent = "gps">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.00001" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.000001" ixy="0.0" ixz="0.0"
          iyy="0.000001" iyz="0.0"
          izz="0.000002"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: gps -->
</robot>
