<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrus" >

  <!-- base kinematics model -->
  <xacro:include filename="$(find mbzirc2020_task2_common)/robots/default.urdf.xacro" />
  <xacro:arg name="default_battery" default="1"/>
  <xacro:property name="modified_leg_collision_model_height" value="0.1715"/>
  <xacro:robot_model tilt_angle = "10" downward_vio = "0" horizontal_vio = "0" default_battery = "$(arg default_battery)" with_leg="0" />

  <!--  The following values model the aluminum peripherial case for the
        D435 camera, with the camera joint represented by the actual
        peripherial camera tripod mount -->
  <xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
  <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
  <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
  <xacro:property name="d435_cam_width" value="0.090"/>
  <xacro:property name="d435_cam_height" value="0.025"/>
  <xacro:property name="d435_cam_depth" value="0.02505"/>
  <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

  <!--  The following offset is relative the the physical D435 camera peripherial
        camera tripod mount -->
  <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
  <xacro:property name="d435_cam_depth_py" value="0.0175"/>
  <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

  <!-- special battery arrangement -->

  <xacro:if value="${$(arg default_battery) == 0}">
    <xacro:extra_module name = "bat1" parent = "link2" visible = "1"
                        model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" scale="0.001">
      <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.4108"/>
        <inertia
            ixx="0.0001" iyy="0.0006" izz="0.0006"
            ixy="0.0" ixz="0.0"  iyz="0.0"/>
      </inertial>
    </xacro:extra_module>

    <xacro:extra_module name = "bat2" parent = "link3" visible = "1"
                        model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" scale="0.001">
      <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.4108"/>
        <inertia
            ixx="0.0001" iyy="0.0006" izz="0.0006"
            ixy="0.0" ixz="0.0"  iyz="0.0"/>
      </inertial>
    </xacro:extra_module>
  </xacro:if>

  <!-- processor: intel upboard -->
  <!-- TODO: change to brix -->
  <xacro:extra_module name = "pc" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/processor/intel_upboard_fixed_joint_unit.dae" >
    <origin xyz="${link_length / 2 + 0.2845} 0.011 0.016" rpy="0 0 ${pi}"/>
    <inertial>
      <mass value = "0.117" />
      <origin xyz="${21 * 0.001} ${4 * 0.001} ${12 * 0.001}" rpy="0 0 0"/>
      <inertia
          ixx="0.00004" ixy="0.0" ixz="0.0"
          iyy="0.00008" iyz="0.0"
          izz="0.00011"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: intel upboard -->

  <!-- sensor -->
  <!-- 1. downward rs-t265 (VIO) -->
  <xacro:extra_module name = "realsense1_pose_frame" parent = "link3" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/downward_realsense_unit.STL">
    <origin xyz="${link_length/2 - 0.111} 0.0 -0.022" rpy="${pi} ${pi/2} ${pi/2}"/>
    <inertial>
      <mass value = "0.065" /> <!-- sensor + usb-cable -->
      <origin xyz="-0.009 -0.01 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: rs-5265 -->

  <!-- 2. Realsense D435 -->
    <!-- TODO: accurate intertia parameters and position -->
  <xacro:extra_module name = "rs_d435_mount" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/rs_d435_unit2.STL">
    <origin xyz="${link_length / 2} 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </xacro:extra_module>
  <joint name="rs_d435_servo_joint" type="revolute">
    <limit effort="0.2" lower="0" upper="1.8" velocity="0.1"/>
    <parent link="link2"/>
    <child link="rs_d435_servo"/>
    <origin xyz="${link_length / 2 + 0.20395} 0.02495 -0.038" rpy="0 0 ${pi/4}"/>
    <axis xyz="-1 0 0"/>
    <dynamics damping="0.01" friction="0.0"/>
  </joint>
  <link name="rs_d435_servo">
    <inertial>
      <mass value = "0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </link>

  <xacro:extra_module name = "rs_d435_unit" parent = "rs_d435_servo" visible = "1" model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/rs_d435_unit1.STL">
    <origin xyz="0.05275 0.01005 0" rpy="0 0 ${pi / 2}"/>
    <inertial>
      <mass value = "0.124" /> <!-- includes usb cable, servo, mounts -->
      <origin xyz="-0.01005 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" iyy="0.0001" izz="0.0002"
          ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:extra_module>

  <!-- rs_d435_link is the parrent of sensors' frame, identical to rs_d435_left_ir_frame  -->
  <xacro:extra_module name = "rs_d435_link" parent = "rs_d435_unit" visible = "0" > 
    <origin xyz="-0.008 0.0175 0 " rpy="0 0 0"/>
    <inertial>
      <mass value = "0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <!-- camera depth joints and links -->
  <joint name="rs_d435_depth_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="rs_d435_link"/>
    <child link="rs_d435_depth_frame" />
  </joint>
  <link name="rs_d435_depth_frame"/>

  <joint name="rs_d435_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    <parent link="rs_d435_depth_frame" />
    <child link="rs_d435_depth_optical_frame" />
  </joint>
  <link name="rs_d435_depth_optical_frame"/>

  <!-- camera left IR joints and links -->
  <joint name="rs_d435_left_ir_joint" type="fixed">
    <origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
    <parent link="rs_d435_depth_frame" />
    <child link="rs_d435_left_ir_frame" />
  </joint>
  <link name="rs_d435_left_ir_frame"/>

  <joint name="rs_d435_left_ir_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    <parent link="rs_d435_left_ir_frame" />
    <child link="rs_d435_left_ir_optical_frame" />
  </joint>
  <link name="rs_d435_left_ir_optical_frame"/>

  <!-- camera right IR joints and links -->
  <joint name="rs_d435_right_ir_joint" type="fixed">
    <origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
    <parent link="rs_d435_depth_frame" />
    <child link="rs_d435_right_ir_frame" />
  </joint>
  <link name="rs_d435_right_ir_frame"/>

  <joint name="rs_d435_right_ir_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    <parent link="rs_d435_right_ir_frame" />
    <child link="rs_d435_right_ir_optical_frame" />
  </joint>
  <link name="rs_d435_right_ir_optical_frame"/>

  <!-- camera color joints and links -->
  <joint name="rs_d435_color_joint" type="fixed">
    <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
    <parent link="rs_d435_depth_frame" />
    <child link="rs_d435_color_frame" />
  </joint>
  <link name="rs_d435_color_frame"/>

  <joint name="rs_d435_color_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    <parent link="rs_d435_color_frame" />
    <child link="rs_d435_color_optical_frame" />
  </joint>
  <link name="rs_d435_color_optical_frame"/>

  ########## sensor wire ###########
  <xacro:extra_module name="cfs_wire_left" parent = "link2" visible = "0" >
    <origin xyz="0.3 0 0 " rpy="0 0 0"/>
    <inertial>
      <mass value = "0.05" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <xacro:extra_module name="cfs_wire_right" parent = "link3" visible = "0" >
    <origin xyz="0.3 0 0 " rpy="0 0 0"/>
    <inertial>
      <mass value = "0.05" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
    </inertial>
  </xacro:extra_module>

  ########## balljoint, sensor, and circle gripper ###########


  <joint name="link12ball_joint11_left" type="fixed">
    <parent link="link1"/>
    <child link="ball_joint11_left"/>
    <origin xyz="0.2925 0.2 0.0" rpy="-1.57 0 0"/>
  </joint>

  <link name="ball_joint11_left">
    <inertial>
      <mass value = "0.01" />
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/ball_joint_gazebo_simple1.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="cfs_sensor_left" type="revolute">
    <parent link="ball_joint11_left"/>
    <child link="ball_joint12_left"/>
    <origin xyz="0 0 0.02" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="0" effort="0" velocity="0"/>
  </joint>

  <link name="ball_joint12_left">
    <inertial>
      <mass value = "0.01" />
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/ball_joint_gazebo_simple1.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="ball_joint1_left" type="revolute">
    <parent link="ball_joint12_left"/>
    <child link="dummy_left"/>
    <origin xyz="0 0 0.02" rpy="1.57 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.4363" upper="0.4363" effort="100" velocity="100"/>
  </joint>

  <link name="dummy_left">
    <inertial>
      <mass value="0.001"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="ball_joint2_left" type="revolute">
    <parent link="dummy_left"/>
    <child link="dummy2_left"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.4363" upper="0.4363" effort="100" velocity="100"/>
  </joint>

  <link name="dummy2_left">
    <inertial>
      <mass value="0.001"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="ball_joint3_left" type="continuous">
    <parent link="dummy2_left"/>
    <child link="ball_joint2_left"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100"/>
  </joint>

  <link name="ball_joint2_left">
    <inertial>
      <mass value = "0.01" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/ball_joint_gazebo_simple2.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="ball_joint22circle_gripper_left" type="fixed">
    <parent link="ball_joint2_left"/>
    <child link="circle_gripper_left"/>
    <origin xyz="-0.068 0.04 -0.068" rpy="0 0 0"/>
  </joint>

  <link name="circle_gripper_left">
    <inertial>
      <mass value = "0.15" />
      <origin xyz="0.068 0 0.068" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/circle_gripper.dae"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/circle_gripper.dae"/>
      </geometry>
    </collision>
  </link>

  <joint name="dummy_gripper_joint_left" type="revolute">
    <parent link="circle_gripper_left"/>
    <child link="dummy_gripper_left"/>
    <origin xyz="0 0.017 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="0" effort="0" velocity="0"/>
  </joint>

  <link name="dummy_gripper_left">
    <inertial>
      <mass value = "0.001" />
      <origin xyz="0.075 0 0.075" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0.075 0 0.075" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.001 0.01"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.075 0 0.075" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.001 0.01"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="link12ball_joint11_right" type="fixed">
    <parent link="link4"/>
    <child link="ball_joint11_right"/>
    <origin xyz="0.2925 0.2 0.0" rpy="-1.57 0 0"/>
  </joint>

  <link name="ball_joint11_right">
    <inertial>
      <mass value = "0.01" />
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/ball_joint_gazebo_simple1.dae"/>
      </geometry>
    </visual>
  </link>
 
  <joint name="cfs_sensor_right" type="revolute">
    <parent link="ball_joint11_right"/>
    <child link="ball_joint12_right"/>
    <origin xyz="0 0 0.02" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="0" effort="0" velocity="0"/>
  </joint>

  <link name="ball_joint12_right">
    <inertial>
      <mass value = "0.01" />
       <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/ball_joint_gazebo_simple1.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="ball_joint1_right" type="revolute">
    <parent link="ball_joint12_right"/>
    <child link="dummy_right"/>
    <origin xyz="0 0 0.02" rpy="1.57 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.4363" upper="0.4363" effort="100" velocity="100"/>
  </joint>

  <link name="dummy_right">
    <inertial>
      <mass value="0.001"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="ball_joint2_right" type="revolute">
    <parent link="dummy_right"/>
    <child link="dummy2_right"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.4363" upper="0.4363" effort="100" velocity="100"/>
  </joint>

  <link name="dummy2_right">
    <inertial>
      <mass value="0.001"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="ball_joint3_right" type="continuous">
    <parent link="dummy2_right"/>
    <child link="ball_joint2_right"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100"/>
  </joint>

  <link name="ball_joint2_right">
    <inertial>
      <mass value = "0.01" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/ball_joint_gazebo_simple2.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="ball_joint22circle_gripper_right" type="fixed">
    <parent link="ball_joint2_right"/>
    <child link="circle_gripper_right"/>
    <origin xyz="-0.068 0.04 -0.068" rpy="0 0 0"/>
  </joint>

  <link name="circle_gripper_right">
    <inertial>
      <mass value = "0.15" />
      <origin xyz="0.068 0 0.068" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/circle_gripper.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/circle_gripper.dae"/>
      </geometry>
    </collision>
  </link>

  <joint name="dummy_gripper_joint_right" type="revolute">
    <parent link="circle_gripper_right"/>
    <child link="dummy_gripper_right"/>
    <origin xyz="0 0.017 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="0" effort="0" velocity="0"/>
  </joint>

  <link name="dummy_gripper_right">
    <inertial>
      <mass value = "0.001" />
      <origin xyz="0.075 0 0.075" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" ixy="0.0000" ixz="0.0000"
          iyy="0.0001" iyz="0.0000" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0.075 0 0.075" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.001 0.01"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.075 0 0.075" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.001 0.01"/>
      </geometry>
    </collision>
  </link>


  ## transmission

  <transmission name="cfs_sensor_left_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="cfs_sensor_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="cfs_sensor_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="ball_joint1_left_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="ball_joint1_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="ball_joint1_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="ball_joint2_left_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="ball_joint2_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="ball_joint2_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="ball_joint3_left_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="ball_joint3_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="ball_joint3_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="dummy_gripper_joint_left_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="dummy_gripper_joint_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="dummy_gripper_joint_left">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="cfs_sensor_right_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="cfs_sensor_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="cfs_sensor_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="ball_joint1_right_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="ball_joint1_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="ball_joint1_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="ball_joint2_right_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="ball_joint2_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="ball_joint2_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="ball_joint3_right_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="ball_joint3_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="ball_joint3_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="dummy_gripper_joint_right_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="dummy_gripper_joint_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="dummy_gripper_joint_right">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  ##### leg #####
  <xacro:standard_leg_end parent = "link1" self="1">
    <origin xyz="${head_leg_offset} 0.0 0" rpy="0 0 0"/>
  </xacro:standard_leg_end>
  <xacro:standard_leg_joint parent = "link1" self="2">
    <origin xyz="0.6 0.0 0" rpy="0 0 0"/>
  </xacro:standard_leg_joint>
  <xacro:standard_leg_joint parent = "link4" self="3">
    <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
  </xacro:standard_leg_joint>
  <xacro:standard_leg_end parent = "link4" self="4">
    <origin xyz="${end_leg_offset} 0.0 0" rpy="0 0 0"/>
  </xacro:standard_leg_end>
  
  <xacro:macro name="leg_collision_model" params="name parent *origin">
    <joint name="${parent}2${name}" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <xacro:insert_block name="origin" />
    </joint>
    <link name="${name}">
      <inertial>
        <mass value = "0.00001" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <inertia
            ixx="0.000001" ixy="0.000000" ixz="0.0000000"
            iyy="0.000001" iyz="0.000000" izz="0.000001"/>
      </inertial>
      <collision>
        <geometry>
          <box size="0.05 0.05 ${modified_leg_collision_model_height}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:leg_collision_model name = "leg_collision_model1" parent = "leg1">
    <origin xyz="0 0 ${-modified_leg_collision_model_height / 2}" rpy="0 0 0"/>
  </xacro:leg_collision_model>
  <xacro:leg_collision_model name = "leg_collision_model2" parent = "leg2">
    <origin xyz="0 0 ${-modified_leg_collision_model_height / 2}" rpy="0 0 0"/>
  </xacro:leg_collision_model>
  <xacro:leg_collision_model name = "leg_collision_model3" parent = "leg3">
    <origin xyz="0 0 ${-modified_leg_collision_model_height / 2}" rpy="0 0 0"/>
  </xacro:leg_collision_model>
  <xacro:leg_collision_model name = "leg_collision_model4" parent = "leg4">
    <origin xyz="0 0 ${-modified_leg_collision_model_height / 2}" rpy="0 0 0"/>
  </xacro:leg_collision_model>
  <xacro:leg_collision_model name = "leg_collision_model5" parent = "link3">
    <origin xyz="0 0 ${-modified_leg_collision_model_height / 2}" rpy="0 0 0"/>
  </xacro:leg_collision_model>

  <transmission name="rs_d435_servo_joint_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rs_d435_servo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rs_d435_servo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
