<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrus" >

  <!-- base kinematics model -->
  <xacro:include filename="$(find hydrus)/urdf/common.xacro" />
  <xacro:include filename="$(find hydrus)/urdf/link.urdf.xacro" />
  <xacro:include filename="$(find mbzirc2020_common)/urdf/fixed_link.urdf.xacro" />

  <xacro:hydrus_link links="4" self="1" rotor_direction="-1" with_battery = "0" with_leg = "0" tilt_mode="0" />
  <xacro:hydrus_fixed_link self="2" rotor_direction="1"  with_battery = "0" with_leg = "0" tilt_angle = "0" />
  <xacro:hydrus_fixed_link self="3" rotor_direction="-1" with_battery = "0" with_leg = "0" tilt_angle = "0" />
  <xacro:hydrus_link links="4" self="4" rotor_direction="1"  with_battery = "0" with_leg = "0" tilt_mode="0" />

  <!-- onboard -->
  <!-- 1.  processor -->
  <!-- 1.1 flight controller -->
  <xacro:extra_module name = "fc" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/processor/spinal_fixed_joint.dae">
    <origin xyz="${link_length / 2 + 0.2432} 0.03951 -0.002" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.0416" />
      <origin xyz="0.0136 0.004 0" rpy="0 0 0"/>
      <inertia
          ixx="0.00001" ixy="0.0" ixz="0.0"
          iyy="0.00001" iyz="0.0"
          izz="0.00002"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: flight controller -->

  <!-- 1.2 processor: neuron for link3 -->
  <xacro:extra_module name = "neuron3" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/processor/neuron_unit.dae" >
    <origin xyz="${link_length / 2 + 0.315} 0.07 0.015" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.01" />
      <origin xyz="0 0  0.01" rpy="0 0 0"/>
      <inertia
          ixx="0.00000" ixy="0.0" ixz="0.0"
          iyy="0.00000" iyz="0.0"
          izz="0.00000"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: processor: neuron -->

  <!-- 1.3 processor: intel upboard -->
  <!-- TODO: change to brix -->
  <xacro:extra_module name = "pc" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/processor/intel_upboard_fixed_joint_unit.dae" >
    <origin xyz="${link_length / 2 + 0.2845} 0.011 0.016" rpy="0 0 ${pi}"/>
    <inertial>
      <mass value = "0.117" />
      <origin xyz="${21 * 0.001} ${4 * 0.001} ${12 * 0.001}" rpy="0 0 0"/>
      <inertia
          ixx="0.00004" ixy="0.0" ixz="0.0"
          iyy="0.00008" iyz="0.0"
          izz="0.00011"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: intel upboard -->


  <!-- 2.  sensor -->
  <!-- 2.1 leddar one -->
  <xacro:extra_module name = "leddarone" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/ledder_one_fixed_joint_unit.dae">
    <origin xyz="${link_length/2 + 0.31814} 0.05614 -0.022" rpy="${pi} 0 0"/>
    <inertial>
      <origin xyz="-0.008 0.0 0.0" rpy="0 0 0"/>
      <mass value="0.02"/>
      <inertia
          ixx="0.0" iyy="0.0" izz="0.0"
          ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: leddar one -->

  <!-- 2.2 gps -->
  <xacro:extra_module name = "gps" parent = "link2" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/sensor/gps_ublox_m8n.dae">
    <origin xyz="${link_length/2 + 0.1925} 0.0 0.152" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0.000000 0.000000 -0.013" rpy="0 0 0"/>
      <mass value="0.042"/>
      <inertia
          ixx="0.00006" iyy="0.00006" izz="0.000007"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
  </xacro:extra_module>
  <xacro:extra_module name = "magnet" parent = "gps">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.00001" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.000001" ixy="0.0" ixz="0.0"
          iyy="0.000001" iyz="0.0"
          izz="0.000002"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: gps -->

  <!-- 2.3 horizontal rs-t265 (option VIO) -->
  <xacro:extra_module name = "realsense1_pose_frame" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/center_leg_rs_t265_unit.STL">
    <origin xyz="${link_length/2 + 0.3281} -0.00114 -0.04" rpy="0 0 ${-pi/4}"/>
    <inertial>
      <mass value = "0.073" />
      <origin xyz="-0.01 -0.007 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
     </inertial>
  </xacro:extra_module>

  <!-- 2.4 Realsense D435 -->
  <!-- TODO: accurate intertia parameters and position -->
  <xacro:extra_module name = "rs_d435_mount" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/rs_d435_unit2.STL">
    <origin xyz="${link_length / 2} 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </xacro:extra_module>
  <joint name="rs_d435_servo_joint" type="revolute">
    <limit effort="0.2" lower="0" upper="1.8" velocity="0.1"/>
    <parent link="link2"/>
    <child link="rs_d435_servo"/>
    <origin xyz="${link_length / 2 + 0.20395} 0.02495 -0.038" rpy="0 0 ${pi/4}"/>
    <axis xyz="-1 0 0"/>
    <dynamics damping="0.01" friction="0.0"/>
  </joint>
  <link name="rs_d435_servo">
    <inertial>
      <mass value = "0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </link>

  <xacro:extra_module name = "rs_d435_unit" parent = "rs_d435_servo" visible = "1" model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/rs_d435_unit1.STL">
    <origin xyz="0.05275 0.01005 0" rpy="0 0 ${pi / 2}"/>
    <inertial>
      <mass value = "0.124" /> <!-- includes usb cable, servo, mounts -->
      <origin xyz="-0.01005 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0001" iyy="0.0001" izz="0.0002"
          ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:extra_module>

  <!-- rs_d435_link is the parrent of sensors' frame, identical to rs_d435_left_ir_frame  -->
  <xacro:extra_module name = "rs_d435_link" parent = "rs_d435_unit" visible = "0" > 
    <origin xyz="-0.008 0.0175 0 " rpy="0 0 0"/>
    <inertial>
      <mass value = "0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
	  ixx="0.0" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="0.0"/>
    </inertial>
  </xacro:extra_module>
  
  
  <transmission name="rs_d435_servo_joint_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rs_d435_servo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rs_d435_servo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- special battery arrangement -->
  <xacro:extra_module name = "bat1" parent = "link1" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" scale="0.001">
    <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.4108"/>
      <inertia
          ixx="0.0001" iyy="0.0006" izz="0.0006"
          ixy="0.0" ixz="0.0"  iyz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <xacro:extra_module name = "bat2" parent = "link4" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" scale="0.001">
    <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.4108"/>
      <inertia
          ixx="0.0001" iyy="0.0006" izz="0.0006"
          ixy="0.0" ixz="0.0"  iyz="0.0"/>
    </inertial>
  </xacro:extra_module>


  <!-- actuated and handmade caster when ground_mode -->
  <!-- actuated legs -->
  <!-- in the second link -->
  <xacro:extra_module name = "actuated_leg1_stationary_part" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/l16_100mm_in.STL">
    <origin xyz="${head_leg_offset} -0.019 0.0186" rpy="${pi/2} 0 ${pi}"/>
    <inertial>
      <mass value = "0.0719" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.000155" ixy="0.0" ixz="0.0"
          iyy="0.000004" iyz="0.0"
          izz="0.000154"/>
    </inertial>
  </xacro:extra_module>

  <joint name="actuated_leg1_joint" type="prismatic">
    <limit effort="50" lower="0" upper="0.1" velocity="1"/>
    <parent link="actuated_leg1_stationary_part"/>
    <child link="actuated_leg1_movable_part"/>
    <origin rpy="0 0 0" xyz="0 -0.112 0"/>
    <axis xyz="0 -1 0"/>
    <dynamics damping="0.1" friction="0.01"/>
  </joint>

  <transmission name="actuated_leg1_joint_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="actuated_leg1_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="actuated_leg1_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <link name="actuated_leg1_movable_part">
    <inertial>
      <origin xyz="0 0.000000 0" rpy="0 0 0"/>
      <mass value="0.01871"/>
      <inertia
          ixx="0.0000320" iyy="0.0000308" izz="0.00000174"
          ixy="0.000" ixz="0.000" iyz="0.000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${-pi/2} ${pi*3/4} 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_pipe_mirror.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} 0 0" xyz="0 ${0.1435/2-0.0435} 0"/>
      <geometry>
        <cylinder length="0.1435" radius="0.0045"/>
      </geometry>
    </collision>
  </link>

  <joint name="actuated_leg1_wheel_joint" type="fixed">
    <parent link="actuated_leg1_movable_part"/>
    <child link="actuated_leg1_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="${-0.00147/1.41421356237} -0.0375 ${-0.00147/1.41421356237}" rpy="${-pi/2} ${-pi/4} 0"/>
  </joint>

  <link name="actuated_leg1_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05282"/>
      <inertia
          ixx="0.0000222" iyy="0.0000180" izz="0.0000222"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_wheel.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} 0 0" xyz="0 0.01435 0"/>
      <geometry>
        <cylinder length="0.008" radius="0.02816"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="${pi/2} 0 0" xyz="0 -0.01435 0"/>
      <geometry>
        <cylinder length="0.008" radius="0.02816"/>
      </geometry>
    </collision>
  </link>

  <!-- in the thrid links -->
  <xacro:extra_module name = "actuated_leg2_stationary_part" parent = "link3" visible = "1"
                      model_url = "package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/l16_100mm_in.STL">
    <origin xyz="${end_leg_offset} -0.019 0.0186" rpy="${pi/2} 0 ${pi}"/>
    <inertial>
      <mass value = "0.0719" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.000155" ixy="0.0" ixz="0.0"
          iyy="0.000004" iyz="0.0"
          izz="0.000154"/>
    </inertial>
  </xacro:extra_module>

  <joint name="actuated_leg2_joint" type="prismatic">
    <limit effort="50" lower="0" upper="0.1" velocity="1"/>
    <parent link="actuated_leg2_stationary_part"/>
    <child link="actuated_leg2_movable_part"/>
    <origin rpy="0 0 0" xyz="0 -0.112 0"/>
    <axis xyz="0 -1 0"/>
    <dynamics damping="0.1" friction="0.01"/>
  </joint>

  <transmission name="actuated_leg2_joint_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="actuated_leg2_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="actuated_leg2_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="actuated_leg2_movable_part">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01871"/>
      <inertia
          ixx="0.0000320" iyy="0.0000308" izz="0.00000174"
          ixy="0.000" ixz="0.000" iyz="0.000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${-pi/2} ${-pi*3/4} 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_pipe.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} 0 0" xyz="0 ${0.1435/2-0.0435} 0"/>
      <geometry>
        <cylinder length="0.1435" radius="0.0045"/>
      </geometry>
    </collision>
  </link>

  <joint name="actuated_leg2_wheel_joint" type="fixed">
    <parent link="actuated_leg2_movable_part"/>
    <child link="actuated_leg2_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="${0.00147/1.41421356237} -0.0375 ${-0.00147/1.41421356237}" rpy="${-pi/2} ${-pi*3/4} 0"/>
  </joint>

  <link name="actuated_leg2_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05282"/>
      <inertia
          ixx="0.0000222" iyy="0.0000180" izz="0.0000222"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_wheel.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} 0 0" xyz="0 0.01435 0"/>
      <geometry>
        <cylinder length="0.008" radius="0.02816"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="${pi/2} 0 0" xyz="0 -0.01435 0"/>
      <geometry>
        <cylinder length="0.008" radius="0.02816"/>
      </geometry>
    </collision>
  </link>

  <!-- handmade caster -->
  <!-- in the first link -->
  <joint name="link1_to_handmade_caster1" type="fixed">
    <parent link="link1"/>
    <child link="handmade_caster1_pipe"/>
    <origin xyz="${head_leg_offset+0.001} 0.0 -0.012" rpy="0 0 0"/>
  </joint>

  <link name="handmade_caster1_pipe">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.012000"/>
      <inertia
          ixx="0.00000089523" iyy="0.000035581" izz="0.000035888"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${-pi/2} 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/caster_pipe.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-0.131/2}"/>
      <geometry>
        <cylinder length="0.131" radius="0.006"/>
      </geometry>
    </collision>
  </link>

  <joint name="handmade_caster1_pipe_to_connector_joint" type="continuous">
    <parent link="handmade_caster1_pipe"/>
    <child link="handmade_caster1_connector"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0.0 0.0 -0.131" rpy="0 0 0"/>
  </joint>

  <transmission name="handmade_caster1_pipe_to_connector_joint_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="handmade_caster1_pipe_to_connector_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="handmade_caster1_pipe_to_connector_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="handmade_caster1_connector">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.009"/>
      <inertia
          ixx="0.000002235" iyy="0.000002515" izz="0.00000298"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/caster_connector.STL"/>
      </geometry>
    </visual>
  </link>

  <joint name="handmade_caster1_connector_to_wheel_joint" type="fixed">
    <parent link="handmade_caster1_connector"/>
    <child link="handmade_caster1_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0.019 0.0 -0.006" rpy="0 0 0"/>
  </joint>

  <link name="handmade_caster1_wheel">
    <inertial>
      <origin xyz="0.000000 0.000000 0.000000" rpy="0 0 0"/>
      <mass value="0.056"/>
      <inertia
          ixx="0.0000253" iyy="0.0000166" izz="0.0000253"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
   </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/wheel.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${60 / 2 * 0.001}"/>
      </geometry>
    </collision>
  </link>

  <!-- in the forth link -->
  <joint name="link4_to_handmade_caster2" type="fixed">
    <parent link="link4"/>
    <child link="handmade_caster2_pipe"/>
    <origin xyz="${end_leg_offset-0.001} 0.0 -0.012" rpy="0 0 0"/>
  </joint>

  <link name="handmade_caster2_pipe">
    <inertial>
      <origin xyz="0.000000 0.000000 0.000000" rpy="0 0 0"/>
      <mass value="0.012000"/>
      <inertia
          ixx="0.00000089523" iyy="0.000035581" izz="0.000035888"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${-pi/2} 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/caster_pipe.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${-0.131/2}"/>
      <geometry>
        <cylinder length="0.131" radius="0.006"/>
      </geometry>
    </collision>
  </link>

  <joint name="handmade_caster2_pipe_to_connector_joint" type="continuous">
    <parent link="handmade_caster2_pipe"/>
    <child link="handmade_caster2_connector"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0.0 0.0 -0.131" rpy="0 0 0"/>
  </joint>

  <transmission name="handmade_caster2_pipe_to_connector_joint_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="handmade_caster2_pipe_to_connector_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="handmade_caster2_pipe_to_connector_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="handmade_caster2_connector">
    <inertial>
      <origin xyz="0.000000 0.000000 0.00000" rpy="0 0 0"/>
      <mass value="0.009"/>
      <inertia
          ixx="0.000002235" iyy="0.000002515" izz="0.00000298"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/caster_connector.STL"/>
      </geometry>
    </visual>
  </link>

  <joint name="handmade_caster2_connector_to_wheel_joint" type="fixed">
    <parent link="handmade_caster2_connector"/>
    <child link="handmade_caster2_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0.019 0.0 -0.006" rpy="0 0 0"/>
  </joint>

  <link name="handmade_caster2_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.056"/>
      <inertia
          ixx="0.0000253" iyy="0.0000166" izz="0.0000253"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/wheel.STL"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${60 / 2 * 0.001}"/>
      </geometry>
    </collision>
  </link>
</robot>
