<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx" >

  <!-- ground_mode flag -->
  <xacro:property name="ground_mode" value="0" />
  <xacro:property name="fixed_leg" value="0" />

  <!-- base kinematics model -->
  <xacro:include filename="$(find mbzirc2020_common)/robots/default.urdf.xacro" />
  <xacro:robot_model tilt_angle = "0" horizontal_vio = "0" default_battery = "1" ground_mode = "${ground_mode}" />

  <!-- processor: intel upboard -->
  <!-- TODO: change to brix -->
  <xacro:extra_module name = "pc" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/processor/intel_upboard_fixed_joint_unit.dae" >
    <origin xyz="${link_length / 2 + 0.2845} 0.011 0.016" rpy="0 0 ${pi}"/>
    <inertial>
      <mass value = "0.117" />
      <origin xyz="${21 * 0.001} ${4 * 0.001} ${12 * 0.001}" rpy="0 0 0"/>
      <inertia
          ixx="0.00004" ixy="0.0" ixz="0.0"
          iyy="0.00008" iyz="0.0"
          izz="0.00011"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: intel upboard -->

  <!-- sensor -->
  <!-- 1. Realsense D435 -->
  <!-- TODO: accurate intertia parameters and position -->
  <xacro:extra_module name = "rs_d435_mount" parent = "link2" visible = "1"
                      model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/rs_d435_unit2.STL">
    <origin xyz="${link_length / 2} 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value = "0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </xacro:extra_module>
  <joint name="rs_d435_servo_joint" type="revolute">
    <limit effort="0.2" lower="0" upper="1.6" velocity="0.5"/>
    <parent link="link2"/>
    <child link="rs_d435_servo"/>
    <origin xyz="${link_length / 2 + 0.20395} 0.02495 -0.038" rpy="0 0 ${pi/4}"/>
    <axis xyz="-1 0 0"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>
  <link name="rs_d435_servo">
    <inertial>
      <mass value = "0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </link>

  <xacro:extra_module name = "rs_d435_camera_frame" parent = "rs_d435_servo" visible = "1" model_url = "package://mbzirc2020_common/urdf/mesh/modules/sensor/rs_d435_unit1.STL">
    <origin xyz="0.05275 0.01005 0" rpy="0 0 ${pi / 2}"/>
    <inertial>
      <mass value = "0.095" />
      <origin xyz="-0.01005 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.00006" ixy="0.0" ixz="0.00006"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </xacro:extra_module>
  <xacro:extra_module name = "rs_d435_camera_optical_frame" parent = "rs_d435_camera_frame">
    <origin xyz="0 0 0" rpy="${-pi / 2} 0 ${-pi / 2}"/>
    <inertial>
      <mass value = "0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <transmission name="rs_d435_servo_joint_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rs_d435_servo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rs_d435_servo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <!-- gripper -->
  <!-- TODO: add gripper at the ends -->

  <!-- actuated and omni leg when ground_mode -->
  <xacro:if value = "${ground_mode}">
    <!-- actuated legs -->
    <!-- in the second link -->
    <xacro:extra_module name = "actuated_leg1_stationary_part" parent = "link2" visible = "1"
  			model_url = "package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_stationary_part.dae">
      <origin xyz="${head_leg_offset} 0 0" rpy="${-pi/2} 0 0"/>
      <inertial>
  	<mass value = "0.142" />
  	<origin xyz="0 0 0" rpy="0 0 0"/>
  	<inertia
            ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001"/>
      </inertial>
    </xacro:extra_module>

    <xacro:if value="${fixed_leg}">
      <joint name="actuated_leg1_joint" type="fixed">
  	<parent link="actuated_leg1_stationary_part"/>
  	<child link="actuated_leg1_movable_part"/>
  	<origin rpy="${-pi/2} 0 ${pi}" xyz="-0.0115 0.1042 0"/>
  	<axis xyz="0 0 -1"/>
      </joint>
    </xacro:if>
    <xacro:unless value="${fixed_leg == 1}">
      <joint name="actuated_leg1_joint" type="prismatic">
    	<limit effort="50" lower="0" upper="0.0927" velocity="1"/>
    	<parent link="actuated_leg1_stationary_part"/>
    	<child link="actuated_leg1_movable_part"/>
    	<origin rpy="${-pi/2} 0 ${pi}" xyz="-0.0115 0 0"/> <!-- TODO: tune -y -->
    	<axis xyz="0 0 -1"/>
    	<dynamics damping="0.1" friction="0.01"/>
      </joint>
      
      <transmission name="actuated_leg1_joint_tran">
    	<type>transmission_interface/SimpleTransmission</type>
    	<joint name="actuated_leg1_joint">
    	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    	</joint>
    	<actuator name="actuated_leg1_joint">
    	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    	  <mechanicalReduction>1</mechanicalReduction>
    	</actuator>
      </transmission>
    </xacro:unless>
    
    <link name="actuated_leg1_movable_part">
      <inertial>
  	<origin xyz="-0.002860 0.000000 -0.089840" rpy="0 0 0"/>
  	<mass value="0.107000"/>
  	<inertia
            ixx="0.002466" iyy="0.003026" izz="0.000699"
            ixy="0.000150" ixz="0.001147" iyz="0.000280"/>
      </inertial>
      <visual>
  	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
  	<geometry>
          <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_movable_part.dae"/>
  	</geometry>
      </visual>
      <collision>
  	<origin rpy="0 0 0" xyz="0.0025 0 -0.128"/>
  	<geometry>
          <sphere radius="${55 / 2 * 0.001}"/>
  	</geometry>
      </collision>
    </link>

    <!-- in the thrid links -->
    <xacro:extra_module name = "actuated_leg2_stationary_part" parent = "link3" visible = "1"
  			model_url = "package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_stationary_part.dae">
      <origin xyz="${end_leg_offset} 0.0 0" rpy="${-pi/2} 0 ${pi}"/>
      <inertial>
  	<mass value = "0.142" />
  	<origin xyz="0 0 0" rpy="0 0 0"/>
  	<inertia
            ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001"/>
      </inertial>
    </xacro:extra_module>

    <xacro:if value="${fixed_leg}">
      <joint name="actuated_leg2_joint" type="fixed">
  	<parent link="actuated_leg2_stationary_part"/>
  	<child link="actuated_leg2_movable_part"/>
  	<origin rpy="${-pi/2} 0 ${pi}" xyz="-0.0115 0.1042 0"/>
  	<axis xyz="0 0 -1"/>
      </joint>
    </xacro:if>
    <xacro:unless value="${fixed_leg == 1}">
      <joint name="actuated_leg2_joint" type="prismatic">
    	<limit effort="50" lower="0" upper="0.0927" velocity="1"/>
    	<parent link="actuated_leg2_stationary_part"/>
    	<child link="actuated_leg2_movable_part"/>
    	<origin rpy="${-pi/2} 0 ${pi}" xyz="-0.0115 0 0"/> <!-- TODO: tune -y -->
    	<axis xyz="0 0 -1"/>
    	<dynamics damping="0.1" friction="0.01"/>
      </joint>
      
      <transmission name="actuated_leg2_joint_tran">
    	<type>transmission_interface/SimpleTransmission</type>
    	<joint name="actuated_leg2_joint">
    	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    	</joint>
    	<actuator name="actuated_leg2_joint">
    	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    	  <mechanicalReduction>1</mechanicalReduction>
    	</actuator>
      </transmission>
    </xacro:unless>

    <link name="actuated_leg2_movable_part">
      <inertial>
  	<origin xyz="-0.002860 0.000000 -0.089840" rpy="0 0 0"/>
  	<mass value="0.107000"/>
  	<inertia
            ixx="0.002466" iyy="0.003026" izz="0.000699"
            ixy="0.000150" ixz="0.001147" iyz="0.000280"/>
      </inertial>
      <visual>
  	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
  	<geometry>
          <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/actuated_leg_movable_part.dae"/>
  	</geometry>
      </visual>
      <collision>
  	<origin rpy="0 0 0" xyz="0.0025 0 -0.128"/>
  	<geometry>
          <sphere radius="${55 / 2 * 0.001}"/>
  	</geometry>
      </collision>
    </link>

    <!-- omniwheel normal legs -->
    <!-- in the first link -->
    <joint name="link1_to_leg1" type="fixed">
      <parent link="link1"/>
      <child link="omni_leg1"/>
      <origin xyz="${head_leg_offset} 0.0 0" rpy="0 0 0"/>
      <origin rpy="0 0 0" xyz="-0.0115 0 -0.0115"/>
      <axis xyz="0 0 0"/>
    </joint>

    <link name="omni_leg1">
      <inertial>
  	<origin xyz="0.000000 0.000000 -0.093340" rpy="0 0 0"/>
  	<mass value="0.072000"/>
  	<inertia
            ixx="-0.000617" iyy="-0.000627" izz="0.0000"
            ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
      </inertial>
      <visual>
  	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
  	<geometry>
          <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/passive_stationary_part.dae"/>
  	</geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 -0.002 -0.14"/>
        <geometry>
          <sphere radius="${55 / 2 * 0.001}"/>
        </geometry>
      </collision>
    </link>

    <!-- in the forth link -->
    <joint name="link4_to_leg3" type="fixed">
      <parent link="link4"/>
      <child link="omni_leg2"/>
      <origin xyz="${end_leg_offset} 0.0 0" rpy="0 0 0"/>
      <origin rpy="0 0 0" xyz="-0.0115 0 -0.0115"/>
      <axis xyz="0 0 0"/>
    </joint>

    <link name="omni_leg2">
      <inertial>
  	<origin xyz="0.000000 0.000000 -0.093340" rpy="0 0 0"/>
  	<mass value="0.072000"/>
  	<inertia
            ixx="-0.000617" iyy="-0.000627" izz="0.0000"
            ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
      </inertial>
      <visual>
  	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
  	<geometry>
          <mesh filename="package://mbzirc2020_task2_common/urdf/mesh/modules/mechanical/passive_stationary_part.dae"/>
  	</geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 -0.002 -0.14"/>
        <geometry>
          <sphere radius="${55 / 2 * 0.001}"/>
        </geometry>
      </collision>
    </link>

    <gazebo reference="actuated_leg1_movable_part">
      <mu1>0.11</mu1>
      <mu2>0.11</mu2>
      <fdir1>1 1 0</fdir1>
      <minDepth>0.00</minDepth>
      <selfCollide>false</selfCollide>
    </gazebo>
    
    <gazebo reference="actuated_leg2_movable_part">
      <mu1>0.11</mu1>
      <mu2>0.11</mu2>
      <fdir1>1 1 0</fdir1>
      <minDepth>0.00</minDepth>
      <selfCollide>false</selfCollide>
    </gazebo>
    
    <gazebo reference="omni_leg1">
      <mu1>0.11</mu1>
      <mu2>0.11</mu2>
      <fdir1>1 1 0</fdir1>
      <minDepth>0.00</minDepth>
      <selfCollide>false</selfCollide>
    </gazebo>
    
    <gazebo reference="omni_leg2">
      <mu1>0.11</mu1>
      <mu2>0.11</mu2>
      <fdir1>1 1 0</fdir1>
      <minDepth>0.00</minDepth>
      <selfCollide>false</selfCollide>
    </gazebo>
  </xacro:if>

</robot>
