cover_pose: [1.5, 1.5] # keep closing
close_pose: [1.5, 1.5] # keep closing

initial_waypoints: [[[3.5], [24.4176534, 54.4360147, 3.5]]] ## 2020.02.11 line kashiwa hype playground

initial_yaw_flag: False
initial_yaw: 2.7227574856695784
