cover_pose: [0.76, 0.76] # to check
# close_pose: [1.56, 1.56]
close_pose: [0.76, 0.76]

return_first_waypoint_flag: False
initial_yaw_flag: True

initial_waypoints: [[[2.5], [2.5]]] ## last waypt will rewrite with gps_xy
task1_waiting_waypoint: [[[5.0]]] ## will rewrite with gps_xy
task1_waiting_height_waypoint: [[[5.0]]]


# mbzirc arena A:
# gps: [24.4177357, 54.4362573]
# yaw: -0.35
# B1: 24.4176534, 54.4357721, yaw: 2.64264678955
# B2: 24.4175904, 54.4361528, yaw: -1.36568617821

#### modify following paramters in real chanllenge:
initial_gps_xy: [24.4175904, 54.4361528]
initial_yaw: -1.366
