cover_pose: [0.76, 0.76] # to check
# close_pose: [1.56, 1.56]
close_pose: [0.76, 0.76]

return_first_waypoint_flag: False
initial_yaw_flag: True

initial_waypoints: [[[3.0], [5.5]]] ## last waypt will rewrite with gps_xy
task1_waiting_waypoint: [[[8.5]]] ## will rewrite with gps_xy
task1_waiting_height_waypoint: [[[8.5]]]


# north-east:
# initial_gps_xy: [24.4177281, 54.4362049]
# initial_yaw: -0.578


# second waypoint for north-east from gazebo
# initial_gps_xy: [24.4177281, 54.4361870]
# initial_yaw: -0.578


# old waypoint (2020.02.22 rehearsal) for north-east:
# initial_gps_xy: [24.4177357, 54.4362573]
# initial_yaw: -0.63

# south-west: 
# initial_gps_xy: [24.4176534, 54.4357721]
# initial_yaw: 2.64264678955

# south-east: no need
# initial_gps_xy: [24.4175904, 54.4361528]
# initial_yaw:: -1.36568617821

# north-west: no need

#### modify following paramters in real chanllenge:
initial_gps_xy: [24.4177281, 54.4362049] 
initial_yaw: -0.58
