cover_pose: [0.76, 0.76] # to check
# close_pose: [1.56, 1.56]
close_pose: [0.76, 0.76]

return_first_waypoint_flag: False
initial_yaw_flag: True

initial_waypoints: [[[3.0], [5.5]]] ## last waypt will rewrite with gps_xy
task1_waiting_waypoint: [[[6.0]]] ## will rewrite with gps_xy
task1_waiting_height_waypoint: [[[6.0]]]


# 1.
# north-east:
# initial_gps_xy: [24.4177281, 54.4362049]
# initial_yaw: -0.578


# second waypoint for north-east from gazebo
# initial_gps_xy: [24.4177281, 54.4361870]
# initial_yaw: -0.578


# old waypoint (2020.02.22 rehearsal) for north-east:
# initial_gps_xy: [24.4177357, 54.4362573]
# initial_yaw: -0.63

# 2.
# south-west: 
# initial_gps_xy: [24.4176235, 54.4358702]
# initial_yaw: 2.57

# second waypoint for south-west: 
# initial_gps_xy: [24.4176534, 54.4357721]
# initial_yaw: 2.64264678955

# 3.
# south-east: 2020.02.23
# initial_gps_xy: [24.4175933, 54.4360905]
# initial_yaw:: -1.51413202286

# 4.
# north-west: no need

#### modify following paramters in real chanllenge:
initial_gps_xy: [24.4175933, 54.4360905] # south-east
initial_yaw: -1.51413202286

