cover_pose: [0.76, 0.76] # to check
# close_pose: [1.56, 1.56]
close_pose: [0.76, 0.76]

return_first_waypoint_flag: False
initial_yaw_flag: True

initial_waypoints: [[[3.0], [5.5]]] ## last waypt will rewrite with gps_xy
task1_waiting_waypoint: [[[8.0]]] ## will rewrite with gps_xy
task1_waiting_height_waypoint: [[[8.0]]]


# mbzirc arena A:
# A1 (north-east):
# initial_gps_xy: [24.4177357, 54.4362573]
# initial_yaw: -0.63

# A2 (north-west): ?

# mbzirc arena B:
# B1 (south-west):
# initial_gps_xy: [24.4176534, 54.4357721]
# initial_yaw: 2.64264678955
# B2 (south-east):
# initial_gps_xy: [24.4175904, 54.4361528]
# initial_yaw:: -1.36568617821

# temp for north-east: gps: [24.4177281, 54.4362049, yaw: -0.577914595604]

#### modify following paramters in real chanllenge:
initial_gps_xy: [24.4177357, 54.4362573]
initial_yaw: -0.63
