cover_pose: [0.76, 0.76] # to check
# close_pose: [1.56, 1.56]
close_pose: [0.76, 0.76]

return_first_waypoint_flag: False
initial_yaw_flag: True

initial_waypoints: [[[2.5], [2.5]]] ## last waypt will rewrite with gps_xy
task1_waiting_waypoint: [[[5.0]]] ## will rewrite with gps_xy
task1_waiting_height_waypoint: [[[5.0]]]



#### modify following paramters in real chanllenge:
initial_gps_xy: [35.8951939, 139.9446149]
initial_yaw: 2.9
