# parameters for script/motion.py in outdoor mode

control_rate : 1.0

navigation_approach_margin : [1.0, 1.0, 0.5]

search_height : 2.0
reach_margin : 1.0
target_timeout : 6.0
approach_height : 1.8
descending_height : 1.2
approach_margin : 0.15
height_margin : 0.15
cover_pose: [0.8, 0.8] # the joint angles for covering
covering_pre_height : 1.8
covering_post_height : 1.2
covering_move_dist : 0.6

close_pose: [1.56, 1.56] # the joint angles  for closing

nav_mode: 5
# search_type: '4_corner_relative'

# search_type: 'rectangular_grid'
# nav_mode: 2
# search_area_number: 2
# initial_waypoints: [[[0,0,0.5], [0, 0, 1]], [[6,6,2]]]
# area_corners : [[[0, 0], [5, 5],0], [[7,7],[10,10],0]]
