global_lookdown_pos_gps: [49.9, 8.90] #lati, long
global_place_channel_center_pos_gps: [49.9000550316, 8.90000008246]
global_place_channel_yaw: 0.0

grasp_joint_angle: [1.4, 1.4]
ungrasp_joint_angle: [0.9, 0.9]
preshape_joint_angle: [0.78, 0.78]
reset_joint_angle: [1.5, 1.5]

object_translation: [0.1, 0.5, 0.0] #in link2 frame
object_yaw: -0.785
object_mass: 1.0

object_lookdown_height: 3.0
object_approach_height: 1.2
object_grasping_height: 0.2
object_yaw_thresh: 0.2
global_first_object_pos: [-1.5, 0.0] #need if no recognition mode
object_interval: 0.6 #object center to center in a lane
lane_interval: 0.75 #constant

global_object_yaw: 3.141
recognition_wait: 1.0

grasping_point: [-0.445, 0.445, 0.00] #in fc frame
grasping_yaw: 2.356 #in fc frame
grasp_land_mode: true
reset_realsense_odom: false
joint_torque_thresh: 5 #[Nm]

place_channel_length: 4.0
global_place_channel_z: 1.7 #[m]
place_z_margin: 0.6 #[m]
place_z_offset: 1.3 #[m]
channel_tf_frame_id: channel_center

disable_alt_sensor: True
alt_sensor_service_name: /estimator/sensor_plugin/alt1/estimate_flag

grid_lookdown: [[0, 2], [0, 1], [0, 0], [0, -1], [0, -2], [1, -2], [1, -1], [1, 0], [1, 1], [1, 2], [2, 2], [2, 1], [2, 0], [2, -1], [2, -2], [3, -2], [3, -1], [3, 0], [3, 1], [3, 2], [4, 2], [4, 1], [4, 0], [4, -1], [4, -2]]
grid_size_lookdown: 0.7

grid_adjust_grasp: [[0, 1], [-1, 1], [-1, 0], [-1, -1], [0, -1], [1, -1], [1, 0], [1, 1], [1, 2], [0, 2], [-1, 2], [-2, 2], [-2, 1], [-2, 0], [-2, -1], [-2, -2], [-1, -2], [0, -2], [1, -2], [2, -2], [2, -1], [2, 0], [2, 1], [2, 2]]
grid_size_adjust_grasp: 0.5

grid_adjust_place: [[0, -1], [0, 0], [0, 1], [0, 2], [-1, 2], [-1, 1], [-1, 0], [-1, -1], [-1, -2], [0, -2], [1, -2], [1, -1], [1, 0], [1, 1], [1, 2]]
grid_size_adjust_place: 0.8
