hls_color_filter:
  h_limit_max: 12
  h_limit_min: 354
  l_limit_max: 251
  l_limit_min: 1
  s_limit_max: 255
  s_limit_min: 72
  use_camera_info: false
  queue_size: 10

dilate_hls_color_filter:
  size: 2
  iterations: 2

opening_hls_color_filter:
  size: 1
  iterations: 2

rectangle_detection_color:
  debug_view: true
  frame_id: target_object_color
  target_object_area: 0.08 #0.2 * 0.6
  target_object_area_margin: 0.02
  object_height: 0.2
  lowest_margin: 10

depth_distance_filter:
  min_depth: 0.3
  use_distance_from_ground: true
  use_otsu_binarization: true
  distance_from_ground: 0.1

opening_depth_distance_filter:
  size: 2
  iterations: 4

rectangle_detection_depth:
  debug_view: true
  frame_id: target_object_depth
  target_object_area: 0.06 #0.2 * 0.6
  target_object_area_margin: 0.02
  object_height: 0.2
  lowest_margin: 20
