<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx" >

  <xacro:include filename="$(find mbzirc2020_task2_common)/urdf/common.xacro" />

  <xacro:macro name="onboards" params="link">

    <!-- flight controller -->
    <xacro:extra_module name = "fc" parent = "link${link}" visible = "1"
                        model_url = "package://hydrus/urdf/mesh/modules/flight_controller/fc_euclid201806.dae"> <!-- same with intel euclid -->
      <origin xyz="${link_length / 2 + 0.2281} ${-4.4*0.001} 0.03533" rpy="0 0 0"/>
      <inertial>
        <mass value = "0.05" />
        <origin xyz="${11.48*0.001} ${4.3*0.001} ${-9.4*0.001}" rpy="0 0 0"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00002"/>
      </inertial>
    </xacro:extra_module>

    <!-- gps -->
    <xacro:extra_module name = "gps" parent = "link${link}" visible = "1"
                        model_url = "package://hydrus/urdf/mesh/modules/sensor/gps_ublox_m8n.dae">
      <origin xyz="${link_length/2 + 0.206} 0.0 0.18" rpy="0 0 0"/>
      <inertial>
        <origin xyz="0.000000 0.000000 -0.062510" rpy="0 0 0"/>
        <mass value="0.053000"/>
        <inertia
            ixx="0.000503" iyy="0.000503" izz="0.000010"
            ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
      </inertial>
    </xacro:extra_module>
    <xacro:extra_module name = "magnet" parent = "gps">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertial>
        <mass value = "0.00001" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
            ixx="0.000001" ixy="0.0" ixz="0.0"
            iyy="0.000001" iyz="0.0"
            izz="0.000002"/>
      </inertial>
    </xacro:extra_module>

    <!-- leddar one -->
    <xacro:extra_module name = "leddarone" parent = "link${link + 1}" visible = "1"
                        model_url = "package://hydrus/urdf/mesh/modules/sensor/leddar_one_tx2_attached_mode.dae">
      <origin xyz="0.0866 0.0 -0.06267" rpy="0 ${pi} 0"/>
      <inertial>
        <origin xyz="-0.007950 0.000000 -0.000140" rpy="0 0 0"/>
        <mass value="0.029000"/>
        <inertia
            ixx="0.000010" iyy="0.000008" izz="0.000008"
            ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
      </inertial>
    </xacro:extra_module>

    <!-- processor: jetson tx2 -->
    <xacro:extra_module name = "pc" parent = "link${link + 1}" visible = "1"
                        model_url = "package://hydrus/urdf/mesh/modules/processor/jetson_tx2.dae"
                        scale="0.001" >
      <origin xyz="0.086 0.0 ${-0.0192}" rpy="${pi/2} 0 ${pi}"/>
      <inertial>
        <mass value = "0.181" />
        <origin xyz="0 ${-5 * 0.001} 0" rpy="0 0 0"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00001"/>
      </inertial>
    </xacro:extra_module>

    <!-- sensor: zed mini with servo -->
    <xacro:extra_module name = "zed_mini_servo_up" parent = "link${link}" visible = "1"
                        model_url = "package://hydrus/urdf/mesh/modules/sensor/zed_mini_servo_up.dae">
      <origin xyz="${link_length/2 + 0.28715} 0.0 -0.04015" rpy="0 0 0"/>
      <inertial>
        <mass value = "0.021" />
        <origin xyz="${-21.77 * 0.001} 0 ${10.3 * 0.001}" rpy="0 0 0"/>
        <inertia
            ixx="0.0" ixy="0.0" ixz="0.0"
            iyy="0.0" iyz="0.0"
            izz="0.0"/>
      </inertial>
    </xacro:extra_module>


    <joint name="zed_mini_servo_joint" type="revolute">
      <limit effort="0.2" lower="-1.6" upper="1.6" velocity="0.1"/>
      <parent link="zed_mini_servo_up"/>
      <child link="zed_mini_servo_down"/>
      <origin rpy="0 0 0" xyz="0 0.0 0"/>
      <axis xyz="1 0 0"/>
      <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="zed_mini_servo_down">
      <inertial>
        <origin xyz="${-21.35 * 0.001} 0 ${-16.4 * 0.001}" rpy="0 0 0"/>
        <mass value="0.079" />
        <inertia
            ixx="0.00001" iyy="0.00012" izz="0.00012"
            ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <visual>
        <origin xyz="${-14.75 * 0.001} 0 ${-19 * 0.001}" rpy="0 ${pi/2} ${-pi}"/>
        <geometry>
          <mesh filename="package://hydrus/urdf/mesh/modules/sensor/zed_mini_servo_down.dae"/>
        </geometry>
      </visual>
    </link>

    <!-- to create the zed center frame -->
    <xacro:extra_module name = "zed_camera_center" parent = "zed_mini_servo_down" visible = "0" >
      <origin xyz="${-14.75 * 0.001} 0 ${-19 * 0.001}" rpy="0 ${pi/2} ${pi/2}"/>
      <inertial>
        <mass value = "0.0" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
            ixx="0.0" ixy="0.0" ixz="0.0"
            iyy="0.0" iyz="0.0"
            izz="0.0"/>
      </inertial>
    </xacro:extra_module>


    <transmission name="zed_mini_servo_joint_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="zed_mini_servo_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="zed_mini_servo_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
</robot>
