# Teleop Basic Param

navigation:
  xy_control_mode: 0
  # World Pos Control Mode: 0
  # World Vel Control Mode: 2
  # Local Vel Control Mode: 3
  # Attitude Control Mode: 4

  takeoff_height: 0.6 #1.2
  outdoor_takeoff_height: 2.0

  # teleop operation
  joy_udp: false
  max_target_vel: 0.5
  joy_target_vel_interval: 0.005  # 0.2 / 20 = 0.01, 0.005 ~ 0.01  m/s
  joy_target_z_interval: 0.02
  max_target_yaw_rate: 1.0 #  0.05
  cmd_vel_lev2_gain : 2.0
  #vel_nav_gain: 0.5 # default: 1.0
  nav_vel_limit: 1.0

  gain_tunning_mode: 0
  max_target_tilt_angle: 0.3
  cmd_angle_lev2_gain : 1.5

  # gps waypoint
  # gps_waypoint_threshold:
  # 0.5: ok for new gps waypoint version
  # 1.0: stable for old gps waypoint version, meaning stable for new version 
  gps_waypoint_threshold: 0.5
  gps_waypoint_check_du: 1.0
